version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      timezone: "Asia/Tokyo"
    open-pull-requests-limit: 0
    groups:
      security-updates:
        applies-to: security-updates
        patterns: ["*"]
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      timezone: "Asia/Tokyo"
    open-pull-requests-limit: 1
    groups:
      security-updates:
        applies-to: security-updates
        patterns: ["*"]
      github-actions-weekly:
        applies-to: version-updates
        patterns: ["*"]
